defaults: &defaults
  encoding: unicode
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  pool: 5
  timeout: 5000
  reaping_frequency: 10
  template: template0


development:
  <<: *defaults
  database: diagramapp_development
  username: postgres
  password: password